/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NowRouteImport } from './routes/now'
import { Route as PlayingRouteImport } from './routes/playing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as WatchingRouteImport } from './routes/watching'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayingRoute = PlayingRouteImport.update({
  id: '/playing',
  path: '/playing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingRoute = WatchingRouteImport.update({
  id: '/watching',
  path: '/watching',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/now': typeof NowRoute
  '/playing': typeof PlayingRoute
  '/projects': typeof ProjectsRoute
  '/watching': typeof WatchingRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/now': typeof NowRoute
  '/playing': typeof PlayingRoute
  '/projects': typeof ProjectsRoute
  '/watching': typeof WatchingRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/now': typeof NowRoute
  '/playing': typeof PlayingRoute
  '/projects': typeof ProjectsRoute
  '/watching': typeof WatchingRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/now' | '/playing' | '/projects' | '/watching' | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/now' | '/playing' | '/projects' | '/watching' | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/now'
    | '/playing'
    | '/projects'
    | '/watching'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NowRoute: typeof NowRoute
  PlayingRoute: typeof PlayingRoute
  ProjectsRoute: typeof ProjectsRoute
  WatchingRoute: typeof WatchingRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playing': {
      id: '/playing'
      path: '/playing'
      fullPath: '/playing'
      preLoaderRoute: typeof PlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching': {
      id: '/watching'
      path: '/watching'
      fullPath: '/watching'
      preLoaderRoute: typeof WatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NowRoute: NowRoute,
  PlayingRoute: PlayingRoute,
  ProjectsRoute: ProjectsRoute,
  WatchingRoute: WatchingRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
